variable "environment" {
  description = "Environment name"
  type        = string
}

variable "notification_email" {
  description = "Email address that receives monitoring alerts"
  type        = string
}

variable "log_group_name" {
  description = "CloudWatch log group monitored for application errors"
  type        = string
}

variable "error_metric_name" {
  description = "CloudWatch metric name generated by the logging module"
  type        = string
  default     = "ApplicationErrors"
}

variable "error_metric_namespace" {
  description = "CloudWatch metric namespace generated by the logging module"
  type        = string
  default     = "ShopSphere/Application"
}

variable "common_tags" {
  description = "Common tags applied to monitoring resources"
  type        = map(string)
  default     = {}
}